services:
  mysql:
    image: mysql:8.0
    container_name: hrsync-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hrsync_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - hrsync-net

# Networks
networks:
  hrsync-net:
    driver: bridge
    name: hrsync-net

# Volumes
volumes:
  mysql: