services:
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: hrsync-backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://hrsync-mysql:3306/hrsync_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - hrsync-net
    depends_on:
      - mysql